name: ci

on:
  push:
    branches: [main, microservice/user]
  pull_request:
    branches: [main, microservice/user]
  workflow_dispatch:

jobs:
  deps-review:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Dependecy Check
    if: github.event_name == 'pull_request'
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Dependency Review
        uses: actions/dependency-review-action@v3

  linter:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: true

      - name: Install
        run: |
          pnpm i
      - name: lint code
        run: |
          pnpm lint
