name: ci

on:
  push:
    branches: [main, microservice/user]
  pull_request:
    branches: [main, microservice/user]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Supported versions ${{matrix.node-versions}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-versions}}

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Lint and Test
        uses: pnpm/action-setup@v2
        with:
          command: pnpm lint && pnpm test
